(function(){"use strict";
function toast(msg){let el=document.getElementById("toast");if(!el){el=document.createElement("div");el.id="toast";el.className="toast";document.body.appendChild(el)}el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
function setStatus(el,text,type="info"){if(!el)return;el.textContent=text;el.className="status"+(type==="loading"?" loading":"")+(type==="ok"?" ok":"")+(type==="warn"?" warn":"")+(type==="error"?" error":"")}
function resultHtml(item,subtitle="Resultado de búsqueda."){const h=DLSRCore.htmlSeguro;const titulo=item.referencia||item.contrato||item.titulo||"Registro";const g=DLSRCore.coordValida(item.lat,item.lon)?DLSRCore.mapsUrl(item):"#";const w=DLSRCore.coordValida(item.lat,item.lon)?DLSRCore.wazeUrl(item):"#";return `<div class="result-head"><div><h2 class="result-title">${h(titulo)}</h2><p class="result-subtitle">${h(subtitle)}</p></div><span class="chip ok">${h(item.tipo||"registro")}</span></div><div class="result-grid">${item.contrato?`<div>Contrato<b>${h(item.contrato)}</b></div>`:""}${item.referencia?`<div>Referencia<b>${h(item.referencia)}</b></div>`:""}<div>Alimentador<b>${h(item.alimentador||"Sin alimentador")}</b></div><div>Latitud<b>${h(item.lat??"")}</b></div><div>Longitud<b>${h(item.lon??"")}</b></div></div><div class="link-row">${DLSRCore.coordValida(item.lat,item.lon)?`<a class="link-chip" href="${g}" target="_blank" rel="noopener">📍 Google Maps</a><a class="link-chip" href="${w}" target="_blank" rel="noopener">🚗 Waze</a>`:""}<button class="link-chip" type="button" data-action="copy">Copiar</button><button class="link-chip" type="button" data-action="share">Compartir</button><button class="link-chip" type="button" data-action="fav">${DLSRCore.esFavorito(item)?"★ Guardado":"☆ Guardar"}</button></div>`}
function bindResultActions(container,item){container._dlsrItem=item;if(container._dlsrBound)return;container._dlsrBound=true;container.addEventListener("click",async e=>{const b=e.target.closest("[data-action]");if(!b)return;const current=container._dlsrItem;if(!current)return;try{if(b.dataset.action==="copy"){await DLSRCore.copiar(DLSRCore.textoCompartir(current));toast("Copiado")}else if(b.dataset.action==="share"){await DLSRCore.compartir(current);toast("Listo")}else if(b.dataset.action==="fav"){const saved=DLSRCore.toggleFavorito(current);b.textContent=saved?"★ Guardado":"☆ Guardar";toast(saved?"Guardado":"Eliminado")}}catch(_){toast("No fue posible completar la acción")}})}
function popupHtml(item){const h=DLSRCore.htmlSeguro;return `<b>${h(item.referencia||item.contrato||"Registro")}</b><br>${h(item.lat)}, ${h(item.lon)}<br>${h(item.alimentador||"Sin alimentador")}<br><a href='${DLSRCore.mapsUrl(item)}' target='_blank' rel='noopener'>Google Maps</a> | <a href='${DLSRCore.wazeUrl(item)}' target='_blank' rel='noopener'>Waze</a>`}
function crearMapa(id="map"){const el=document.getElementById(id);el.className="map";el.innerHTML="";const map=L.map(id,{zoomControl:true}).setView([13.7,-89.2],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"&copy; OpenStreetMap"}).addTo(map);setTimeout(()=>map.invalidateSize(),100);return map}
function markerIcon(color="blue"){return L.icon({iconUrl:`https://maps.gstatic.com/mapfiles/ms2/micons/${color}-dot.png`,iconSize:[30,30],iconAnchor:[15,30]})}
window.DLSRUI={toast,setStatus,resultHtml,bindResultActions,popupHtml,crearMapa,markerIcon};
})();
